#FROM quay.io/fedora/fedora:42
FROM quay.io/podman/stable:latest

RUN dnf -y update && \
    dnf install -y git \
                   nss \
                   atk \
                   at-spi2-atk \
                   cups-libs \
                   gtk3 \
                   fluxbox \
                   tigervnc-server \
                   xorg-x11-fonts-Type1 \
                   novnc \
                   supervisor \
                   xdpyinfo \
                   podman \
                   xterm \
                   dbus && \
                   rm -rf /var/cache /var/log/dnf* /var/log/yum.*

# Install Node.js + pnpm
ENV NODE_VERSION=20.18.1
RUN curl -SLO "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz" && \
    tar -xzf "node-v$NODE_VERSION-linux-x64.tar.gz" -C /usr/local --strip-components=1 && \
    rm -f "node-v$NODE_VERSION-linux-x64.tar.gz" && \
    npm install -g pnpm

COPY entrypoint.sh /entrypoint.sh
COPY supervisord.conf /etc/supervisord.conf
COPY fluxbox /usr/share/fluxbox/init
# RUN useradd -u 1000 podman-desktop && echo podman-desktop:10000:5000 > /etc/subuid && echo podman-desktop:10000:5000 > /etc/subgid

#VOLUME /var/lib/containers
##VOLUME /home/podman/.local/share/containers

# Initialize conf files
#ADD https://raw.githubusercontent.com/containers/image_build/refs/heads/main/podman/containers.conf /etc/containers/containers.conf
#ADD https://raw.githubusercontent.com/containers/image_build/refs/heads/main/podman/podman-containers.conf /home/podman/.config/containers/containers.conf

# Disable telemetry
RUN mkdir -p /home/podman/.local/share/containers/podman/configuration && \
    echo '{"telemetry.enabled": false, "telemetry.check": true}' > /home/podman/.local/share/containers/podman/configuration/settings.json

# # chmod containers.conf and adjust storage.conf to enable Fuse storage.
# RUN chmod 644 /etc/containers/containers.conf;
# RUN sed -e 's|^#mount_program|mount_program|g' \
#            -e '/additionalimage.*/a "/var/lib/shared",' \
#            -e 's|^mountopt[[:space:]]*=.*$|mountopt = "nodev,fsync=0"|g' \
#            /usr/share/containers/storage.conf \
#            > /etc/containers/storage.conf
# #RUN mkdir -p /var/lib/shared/overlay-images /var/lib/shared/overlay-layers /var/lib/shared/vfs-images /var/lib/shared/vfs-layers; touch /var/lib/shared/overlay-images/images.lock; touch /var/lib/shared/overlay-layers/layers.lock; touch /var/lib/shared/vfs-images/images.lock; touch /var/lib/shared/vfs-layers/layers.lock
# RUN mkdir -p /var/lib/shared/overlay-images \
#              /var/lib/shared/overlay-layers \
#              /var/lib/shared/vfs-images \
#              /var/lib/shared/vfs-layers && \
#     touch /var/lib/shared/overlay-images/images.lock && \
#     touch /var/lib/shared/overlay-layers/layers.lock && \
#     touch /var/lib/shared/vfs-images/images.lock && \
#     touch /var/lib/shared/vfs-layers/layers.lock
# Set permissions
# RUN chown podman-desktop:podman-desktop -R /home/podman-desktop && chmod 644 /etc/containers/containers.conf && \
#     mkdir -p /var/lib/shared/overlay-images /var/lib/shared/overlay-layers /var/lib/shared/vfs-images /var/lib/shared/vfs-layers; touch /var/lib/shared/overlay-images/images.lock; touch /var/lib/shared/overlay-layers/layers.lock; touch /var/lib/shared/vfs-images/images.lock; touch /var/lib/shared/vfs-layers/layers.lock && \
#     mkdir -p /run/user/1000 && chown -R podman-desktop:podman-desktop /run/user/1000

# Setup VNC server
RUN mkdir /home/podman/.vnc \
&& echo "password" | vncpasswd -f > /home/podman/.vnc/passwd \
&& chmod 600 /home/podman/.vnc/passwd

# Create an .Xauthority file
RUN touch /home/podman/.Xauthority

# Expose port for VNC
EXPOSE 8080

ENV _CONTAINERS_USERNS_CONFIGURED=""

# Socket path for podman
ENV XDG_RUNTIME_DIR=/run/user/1000

ENTRYPOINT [ "/entrypoint.sh" ]
USER "podman"
CMD ["tail", "-f", "/dev/null"]

# [podman|docker] build -t quay.io/podman/devcontainer-parent:next -f Containerfile .
